apiVersion: v1
kind: Service
metadata:
  name: network-node-identity
  namespace: {{.HostedClusterNamespace}}
  labels:
    app: network-node-identity
    hypershift.openshift.io/allow-guest-webhooks: "true"
  annotations:
    network.operator.openshift.io/cluster-name: {{.ManagementClusterName}}
# If the default CAConfigMap 'openshift-service-ca.crt' was used then the HostedCluster isn't reconciling the secret, so
# we need to add the annotation so service-ca creates the secret
{{- if eq .CAConfigMap "openshift-service-ca.crt"}}
    service.beta.openshift.io/serving-cert-secret-name: network-node-identity-secret
{{- end}}
spec:
  ports:
    - name: webhook
      port: {{.NetworkNodeIdentityPort}}
      targetPort: {{.NetworkNodeIdentityPort}}
  selector:
    app: network-node-identity
