---
# The ovnconfig config file. Used by both node and master processes.
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovnkube-config
  namespace: openshift-ovn-kubernetes
data:
  ovnkube.conf:   |-
    [default]
    mtu="{{.MTU}}"
    cluster-subnets="{{.OVN_cidr}}"
    encap-port="{{.GenevePort}}"

    [kubernetes]
    service-cidrs="{{.OVN_service_cidr}}"
    ovn-config-namespace="openshift-ovn-kubernetes"
    apiserver="{{.K8S_APISERVER}}"

    {{if .OVNHybridOverlayEnable}}
    [hybridoverlay]
    enabled=true
      {{if .OVNHybridOverlayNetCIDR}}
    cluster-subnets={{.OVNHybridOverlayNetCIDR}}
      {{end}}
      {{if  .OVNHybridOverlayVXLANPort}}
    hybrid-overlay-vxlan-port={{.OVNHybridOverlayVXLANPort}}
      {{end}}
    {{end}}

    [gateway]
    mode=local
    nodeport=true
